# Generated by Django 5.2 on 2025-04-07 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacedBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmaker', models.CharField(max_length=100)),
                ('bet_type', models.CharField(max_length=100)),
                ('odds', models.FloatField()),
                ('stake', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_value', models.FloatField()),
                ('true_probability', models.FloatField()),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('won', 'Won'), ('lost', 'Lost'), ('push', 'Push'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('result_updated_at', models.DateTimeField(blank=True, null=True)),
                ('profit_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='betting.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placed_bets', to=settings.AUTH_USER_MODEL)),
                ('value_bet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placed_bets', to='betting.valuebet')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_edge_threshold', models.FloatField(default=1.03)),
                ('bankroll', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('kelly_fraction', models.FloatField(default=0.5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBookmakerPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmaker', models.CharField(max_length=100)),
                ('is_enabled', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmaker_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'bookmaker')},
            },
        ),
    ]
