# Generated by Django 5.2 on 2025-04-07 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0002_placedbet_userprofile_userbookmakerpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_edge_threshold',
            field=models.FloatField(default=1.0),
        ),
        migrations.CreateModel(
            name='ValueBetTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmaker', models.CharField(max_length=100)),
                ('bet_type', models.CharField(max_length=100)),
                ('odds', models.FloatField()),
                ('true_probability', models.FloatField()),
                ('expected_value', models.FloatField()),
                ('bet_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('theoretical_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('result', models.CharField(choices=[('pending', 'Pending'), ('won', 'Won'), ('lost', 'Lost'), ('push', 'Push'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('result_updated_at', models.DateTimeField(blank=True, null=True)),
                ('identified_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='betting.game')),
                ('value_bet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracker', to='betting.valuebet')),
            ],
            options={
                'ordering': ['-identified_at'],
            },
        ),
    ]
